name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    
    - name: Build makelogo
      run: |
        cd PT5230/PT8633/TPD/900_NR
        cd "8633_915_ DR1"
        cd "grafik filer"
        cl /D_USE_MATH_DEFINES makelogo.c
    - name: Build filter
      run: |
        cd PT5230/PT8633/TPD/900_NR
        cd "8633_915_ DR1"
        cd "grafik filer"
        cl /D_USE_MATH_DEFINES filter.c
        dir
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: "PT5230/PT8633/TPD/900_NR/8633_915_ DR1/grafik filer/*.exe"
