name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build makelogo
      run: |
        call C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd PT5230/PT8633/TPD/900_NR
        cd "8633_915_ DR1"
        cd "grafik filer"
        cl makelogo.c
    - name: Build filter
      run: |
        call C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd PT5230/PT8633/TPD/900_NR
        cd "8633_915_ DR1"
        cd "grafik filer"
        cl filter.c
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: "PT5230/PT8633/TPD/900_NR/8633_915_ DR1/grtafik files/*.exe"
